# Generated by Django 6.1 on 2026-09-30 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_dish_image_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('В обработке', 'Processing'), ('Готово', 'Ready'), ('Завершён', 'Completed'), ('Отменён', 'Cancelled')], default='processing', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.profile'),
        ),
    ]
