# Generated by Django 6.1 on 2026-10-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_status_alter_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='image',
        ),
        migrations.AddField(
            model_name='category',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='categories', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='dish',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='dishes', verbose_name='Изображение'),
        ),
    ]
